name: Daily Useless Fact

on:
  schedule:
    - cron: "0 0 * * *" # 매일 UTC 0시 (KST 오전 9시)
  workflow_dispatch: # 수동 실행도 가능

jobs:
  update-fact:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. 필요한 패키지 설치
      - name: Install dependencies
        run: |
          pip install requests

      # 4. 스크립트 실행 (README 업데이트)
      - name: Run useless fact script
        run: python scripts/useless_fact_readme.py

      # 5. 변경 내용 커밋 & 푸시
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update useless fact for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
